---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 2
    memory: 1024

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.4
suites:
  - name: default
    run_list:
      - recipe[mysql::server]
      - recipe[passenger_apache2::mod_rails]
      - recipe[redmine::default]
    attributes:
      mysql:
        server_root_password: 'root'
        server_repl_password: 'root'
        server_debian_password: 'root'
      redmine:
        db:
          password: 'password'
